# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed order', max_length=255)),
                ('price', models.IntegerField()),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('DN', 'Completed'), ('SH', 'In shipping'), ('PR', 'Being processed'), ('WT', 'Awaiting at delivery')], default='PR', max_length=2)),
                ('status_timedate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ship_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shipping'),
        ),
    ]
