# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160423_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, to='shop.Tag'),
        ),
    ]
