# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160320_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping',
            new_name='ShippingMethod',
        ),
    ]
