# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20160320_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('bill', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='shop.Cart')),
                ('laid_off', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_laid_off_cart', to='shop.Cart')),
                ('orders', models.ManyToManyField(to='shop.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
