# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shopuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-status_timedate']},
        ),
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'verbose_name': 'Shipping method'},
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='username',
        ),
    ]
