# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20160324_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(default='Bob', max_length=50),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='last_name',
            field=models.CharField(default='Bobbys', max_length=50),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='username',
            field=models.CharField(default='user<built-in function id>', max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='bill',
            field=models.FloatField(default=0),
        ),
    ]
