# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20160324_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='laid_off',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='orders',
        ),
        migrations.DeleteModel(
            name='ShopUser',
        ),
    ]
