# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('shop', '0009_auto_20160324_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.TextField(default='')),
                ('bill', models.FloatField(default=0)),
                ('discount', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='shop.Cart')),
                ('laid_off', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_laid_off_cart', to='shop.Cart')),
                ('orders', models.ManyToManyField(to='shop.Order')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
